idf_component_register(
    SRCS
        "main.c"
        "app/app_activity.c"
        "app/app_context.c"
        "app/app_display.c"
        "app/app_imu.c"
        "app/app_power.c"
        "app/app_settings.c"
        "app/app_time.c"
        "ui/core/ui_core.c"
        "ui/core/ui_core_state.c"
        "ui/core/ui_dialogs.c"
        "ui//core/ui_gestures.c"
        "ui/core/ui_layout.c"
        "ui/core/ui_pages.c"
        "ui/settings/ui_settings_page.c"
        "ui/data/ui_data_page.c"
        "ui/settings/ui_status_bar.c"
        "ui/settings/ui_theme.c"
        "ui/menu/ui_menu_page.c"
        "ui/activity_summary/ui_activity_summary_page.c"
        "ui/activity_summary/ui_activity_detail_page.c"
        "ui/interval/ui_interval_setup_page.c"
        "ui/interval/ui_interval_data_page.c"
        "interval_program/interval_program.c"
        
    INCLUDE_DIRS
        "."
        "app"
        "ui"
        "ui/core"
        "ui/activity_summary"
        "ui/data"
        "ui/interval"
        "ui/menu"
        "ui/settings"
        "interval_program"
    REQUIRES
        lcd_st7789
        touch_cst328
        esp_lvgl_port
        i2c_helper
        qmi8658
        stroke_detection
        sd_mmc_helper
        ble
        rtc_pcf85063
        pwr_key
        battery_drv
        activity
        activity_log
        activity_store
        gps_gtu8
        nvs_helper
)
