idf_component_register(
    SRCS
        "main.c"
        "ui/ui_core.c"
        "ui/settings/ui_settings_page.c"
        "ui/ui_data_page.c"
        "ui/settings/ui_status_bar.c"
        "ui/settings/ui_theme.c"
        "ui/ui_menu_page.c"
        "ui/activity_summary/ui_activity_summary_page.c"
        "ui/activity_summary/ui_activity_detail_page.c"
        "ui/interval/ui_interval_setup_page.c"
        "ui/interval/ui_interval_data_page.c"
        "interval_program/interval_program.c"
        "race_program/race_program.c"
        "ui/race/ui_race_setup_page.c" 
        "ui/race/ui_race_data_page.c"
        
    INCLUDE_DIRS
        "."
        "ui"
        "ui/activity_summary"
        "ui/interval"
        "ui/settings"
        "ui/race"
        "interval_program"
        "race_program"
    REQUIRES
        lcd_st7789
        touch_cst328
        esp_lvgl_port
        i2c_helper
        qmi8658
        stroke_detection
        sd_mmc_helper
        ble
        rtc_pcf85063
        pwr_key
        battery_drv
        activity
        activity_log
        activity_store
        gps_gtu8
        nvs_helper
)
